title: Cyberpunk Luthier
description: Um blog legal
author: Cyberpunkluthier
github: https://github.com/cyberpunkluthier
about: lorem ipsum
disqus_shortname: cyberpunkluthier
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/cyberpunkluthier"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Sobre
      url: /sobre/
    - text: Blog
      url: /blog/
    - text: Zines
      url: /zines/

url: "https://cyberpunkluthier.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
>>>>>>> 96ae3ec (layout 2 pa nois)
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
